'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {SVGRenderer} from 'three/addons/renderers/SVGRenderer.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
export default function Twin({station,selected,onSelect,layer,scenario,cutaway,reset}:any){const host=useRef<HTMLDivElement>(null),api=useRef<any>(null),callback=useRef(onSelect);callback.current=onSelect;const[failed,setFailed]=useState(false);
 useEffect(()=>{if(!host.current)return;let renderer:any;let software=false;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{renderer=new SVGRenderer();renderer.setQuality('low');software=true;}setFailed(false);const el=host.current;if(!software){renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;}renderer.setClearColor(new THREE.Color(0xdde4e7),1);el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive conceptual Antarctic station. Drag to orbit and click buildings to inspect.');const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xdde4e7,80,155);const camera=new THREE.PerspectiveCamera(36,1,.1,250);camera.position.set(47,40,54);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1,0);controls.enableDamping=true;controls.minDistance=24;controls.maxDistance=105;controls.maxPolarAngle=Math.PI*.46;controls.minPolarAngle=.12;scene.add(new THREE.AmbientLight(0xe0e5e8,software?.8:2.2));const sun=new THREE.DirectionalLight(0xd3e7f4,software?1.05:3);sun.position.set(-25,45,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-45;sun.shadow.camera.right=45;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-45;sun.shadow.bias=-.001;scene.add(sun);const rim=new THREE.DirectionalLight(0xa4b3c3,software?.3:1.2);rim.position.set(30,10,-25);scene.add(rim);
 const materials:THREE.Material[]=[];function mat(color:any,metalness=.15){const m=software?new THREE.MeshLambertMaterial({color}):new THREE.MeshStandardMaterial({color,roughness:.75,metalness});materials.push(m);return m}const snow=mat(0xd9e1e2),wall=mat(station==='bharati'?0xb7c6ca:0xc28353),roof=mat(0x607a8a),dark=mat(0x253a49),glass=mat(0x173e53,.6),trim=mat(0xe6a853),steel=mat(0x576978,.6),red=mat(0xb06646),solarMat=mat(0x194d69,.5);const groups:Record<string,THREE.Group>={},roofs:THREE.Object3D[]=[];const pickable:THREE.Object3D[]=[];
 function box(parent:THREE.Object3D,w:number,h:number,d:number,x:number,y:number,z:number,m:THREE.Material){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
 function cylinder(parent:THREE.Object3D,r:number,h:number,x:number,y:number,z:number,m:THREE.Material){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,software?12:28),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
 const ground=new THREE.Mesh(new THREE.CylinderGeometry(38,39.5,1.6,80),snow);ground.position.y=-1.1;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(120,30,0x263641,0x182732);grid.position.y=-2;(grid.material as THREE.LineBasicMaterial).color.setHex(0x233744);scene.add(grid);
 // Deterministic low rock outcrops around the conceptual station perimeter.
 for(let i=0;i<(software?28:56);i++){const a=i*2.39996,r=27+(Math.sin(i*3.7)+1)*5;const geo=new THREE.DodecahedronGeometry(.7+(Math.sin(i*1.6)+1)*1.5,0);const rock=new THREE.Mesh(geo,i%4===0?steel:snow);rock.position.set(Math.cos(a)*r,-.05,Math.sin(a)*r);rock.scale.y=.3;rock.rotation.set(i*.4,i*.8,0);rock.castShadow=true;rock.receiveShadow=true;scene.add(rock)}
 function group(id:string,x:number,z:number){const g=new THREE.Group();g.position.set(x,0,z);g.userData.asset=id;groups[id]=g;scene.add(g);return g}
 function building(id:string,x:number,z:number,w:number,d:number,h:number,raised=false){const g=group(id,x,z),base=raised?2.4:.3;if(raised){for(let xx=-w/2+1;xx<w/2;xx+=3)for(const zz of [-d/2+1,d/2-1])box(g,.35,base,.35,xx,base/2,zz,steel);box(g,w+.5,.3,d+.5,0,base,0,steel)}const shell=box(g,w,h,d,0,base+h/2,0,wall);shell.userData.shell=true;box(g,w+.2,.22,d+.2,0,base+.15,0,trim);const r=box(g,w+.6,.3,d+.6,0,base+h+.1,0,roof);roofs.push(r);for(let xx=-w/2+.8;xx<w/2-.4;xx+=1.6){for(const zz of [-d/2-.025,d/2+.025]){box(g,1.05,.65,.08,xx,base+h*.62,zz,glass);box(g,1.15,.07,.13,xx,base+h*.62+.37,zz,steel)}box(g,.04,h,.03,xx,base+h/2,d/2+.045,steel)}for(let i=0;i<3;i++){const vent=box(g,.65,.5,.9,-w/3+i*w/3,base+h+.48,0,dark);roofs.push(vent)}box(g,.95,1.75,.09,w/2-1,base+.9,d/2+.08,dark);for(let i=0;i<5;i++)box(g,1.7,.18,1.1,w/2-1,base*(1-i/6),d/2+.6+i*.5,steel);return g}
 if(station==='bharati'){const g=building('main',-3,-1,19,8,3.3,true);box(g,19,1,8,0,6.3,0,wall);roofs.forEach(r=>{if(r.parent===g)r.position.y+=1});for(let x=-8;x<9;x+=1.5)box(g,1,.55,.09,x,6.3,4.06,glass);}else{const g=building('main',-6,-2,16,7,3,false);box(g,7,3,8,4,.3+1.5,-5,wall);roofs.push(box(g,7.5,.3,8.5,4,3.5,-5,roof))}
 building('power',13,-8,7,6,3.1);const pg=groups.power;for(let i=0;i<2;i++){cylinder(pg,.25,5.8,-2+i*3,4.5,-2,dark);box(pg,2,1.1,1.4,-1.8+i*3,1.2,0,trim)}building('lab',-13,-13,8,5,2.8);building('water',11,10,6,5,2.6);building('storage',-15,12,8,5,2.8);
 const fg=group('fuel',21,1);for(let i=0;i<3;i++){cylinder(fg,1.45,3,0,1.5,-4+i*3.6,steel);cylinder(fg,1.5,.18,0,3.1,-4+i*3.6,roof);box(fg,.14,2.5,.14,1.5,1.3,-4+i*3.6,trim)}box(fg,5,.4,13,0,-.1,0,dark);
 const cg=group('comms',-4,-18);cylinder(cg,.17,7,0,3.5,0,steel);const dish=new THREE.Mesh(new THREE.SphereGeometry(2.1,32,16,0,Math.PI*2,0,Math.PI*.45),mat(0xc6d5db));dish.rotation.x=Math.PI*.67;dish.position.set(0,7,0);cg.add(dish);cylinder(cg,.07,2,0,7,0,steel);
 const sg=group('solar',-4,17);for(let x=0;x<4;x++)for(let z=0;z<2;z++){const panel=box(sg,3,.15,2,-5+x*3.3,1.2,z*3,solarMat);panel.rotation.x=-.3;cylinder(sg,.07,1.4,-5+x*3.3,.55,z*3,steel);for(let l=0;l<4;l++){const line=box(sg,.025,.17,2,-6.2+x*3.3+l*.75,1.21,z*3,steel);line.rotation.x=-.3}}
 // Utility conduits connect buildings into one station infrastructure model.
 for(const [x,z] of [[13,-8],[11,10],[-13,-13],[-15,12]]){box(scene,Math.abs(x),.22,.45,x/2,.05,0,steel);box(scene,.45,.22,Math.abs(z),x,.05,z/2,steel)}
 // A freestanding flag court: clear of both station footprints and entrance stairs.
 const flagCourt=new THREE.Group();flagCourt.name='Indian flag · 24-spoke Ashoka Chakra';flagCourt.position.set(-3,0,9);flagCourt.rotation.y=Math.PI/4;scene.add(flagCourt);
 cylinder(flagCourt,.55,.3,0,.15,0,steel);cylinder(flagCourt,.075,8.5,0,4.4,0,steel);
 const flagColors=[0xff9933,0xffffff,0x138808].map(color=>new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide}));
 for(let band=0;band<3;band++)box(flagCourt,3,2/3,.04,1.56,7.7-band*2/3,0,flagColors[band]);
 const chakraMaterial=new THREE.MeshBasicMaterial({color:0x000080,side:THREE.DoubleSide});
 // Geometry on both faces remains visible in WebGL and the software renderer.
 for(const face of [-1,1]){
  const wheel=new THREE.Mesh(new THREE.RingGeometry(.263,.289,72),chakraMaterial);wheel.position.set(1.56,7.7-2/3,face*.024);flagCourt.add(wheel);
  const hub=new THREE.Mesh(new THREE.CircleGeometry(.034,24),chakraMaterial);hub.position.set(1.56,7.7-2/3,face*.027);flagCourt.add(hub);
  for(let spoke=0;spoke<24;spoke++){const angle=spoke*Math.PI*2/24;const radius=.139;const mesh=box(flagCourt,.012,.278,.003,1.56+Math.sin(angle)*radius,7.7-2/3+Math.cos(angle)*radius,face*.027,chakraMaterial);mesh.rotation.z=-angle;}
 }
 const pad=new THREE.Mesh(new THREE.RingGeometry(4.1,4.3,64),trim);pad.rotation.x=-Math.PI/2;pad.position.set(15,.02,20);scene.add(pad);box(scene,.3,.04,3,13.9,.05,20,trim);box(scene,.3,.04,3,16.1,.05,20,trim);box(scene,2.4,.04,.3,15,.05,20,trim);
 const rings:Record<string,THREE.Mesh>={};for(const [id,g]of Object.entries(groups)){g.traverse(o=>{if(o instanceof THREE.Mesh){o.userData.asset=id; if((o as THREE.Mesh).material===wall){(o as THREE.Mesh).material=wall.clone();o.userData.shell=true;} pickable.push(o)}});const ring=new THREE.Mesh(new THREE.RingGeometry(4,4.07,64),new THREE.MeshBasicMaterial({color:0x415d77,side:THREE.DoubleSide,transparent:true,opacity:.6}));ring.rotation.x=-Math.PI/2;ring.position.set(g.position.x,.1,g.position.z);scene.add(ring);rings[id]=ring;const beacon=new THREE.Mesh(new THREE.SphereGeometry(.22,12,8),new THREE.MeshBasicMaterial({color:0x34826b}));beacon.position.set(0,id==='main'?8:5,0);g.add(beacon);g.userData.beacon=beacon}
 const selection=new THREE.BoxHelper(groups.main,0x415d77);scene.add(selection);let needsRender=true;controls.addEventListener('change',()=>{needsRender=true});api.current={groups,roofs,rings,selection,camera,controls,wall,renderer,invalidate:()=>{needsRender=true}};let frame=0;let lastFrame=0;const animate=(now=0)=>{frame=requestAnimationFrame(animate);if(software&&now-lastFrame<160)return;lastFrame=now;controls.update();if(!software||needsRender){renderer.render(scene,camera);needsRender=false}};const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();needsRender=true};const ro=new ResizeObserver(resize);ro.observe(el);resize();animate();const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();let down=[0,0];const pointerDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY]};const click=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const rect=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(pickable);if(hits.length)callback.current(hits[0].object.userData.asset)};renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',click);return()=>{cancelAnimationFrame(frame);ro.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose()}});renderer.dispose?.();el.removeChild(renderer.domElement);api.current=null}
 },[station]);
 useEffect(()=>{const a=api.current;if(!a)return;a.selection.setFromObject(a.groups[selected]);Object.entries(a.rings).forEach(([id,ring]:any)=>{ring.visible=id===selected});a.roofs.forEach((r:any)=>r.visible=!cutaway);a.wall.transparent=cutaway;a.wall.opacity=cutaway?.22:1;a.invalidate();for(const[id,g]of Object.entries(a.groups) as any){const color=id==='power'&&scenario==='generator'?0xf2975b:scenario==='outage'?0x9ba5b1:layer==='thermal'?id==='power'?0xf09560:0xe4c178:layer==='energy'?id==='power'?0xf4b052:0x6cb9d0:0x34826b;g.userData.beacon.material.color.setHex(color);g.traverse((o:any)=>{if(o.userData.shell&&o.material){o.material.color.setHex(layer==='status'?(id==='power'&&scenario==='generator'?0xd2925b:station==='bharati'?0xb7c6ca:0xc28353):color);o.material.transparent=cutaway;o.material.opacity=cutaway?.2:1;}})}},[selected,layer,scenario,cutaway,station]);
 useEffect(()=>{const a=api.current;if(a){a.camera.position.set(47,40,54);a.controls.target.set(0,1,0)}},[reset]);
 return <div ref={host} className="three-host">{failed&&<div className="webgl-error"><b>3D rendering is unavailable in this browser.</b><p>Enable WebGL or use another browser. Asset inspection remains available through “Jump to asset”.</p></div>}</div>
}
